name: coverity
on:
  push:
    branches: [2.0]

permissions:
  contents: read

jobs:
  analyze:
    if: github.repository == 'c9s/r3'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Prepare
      run: |
        ./autogen.sh
        ./configure --enable-check
    - uses: vapier/coverity-scan-action@1b6fd4eaba6651aa354c9ea7f48caa1710b4e12e # v1.9.0
      with:
        project: r3
        email: yoanlin93+github@gmail.com
        token: ${{ secrets.COVERITY_TOKEN }}
