name: coverity
on:
  push:
    branches: [2.0]

jobs:
  analyze:
    if: github.repository == 'c9s/r3'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        ./autogen.sh
        ./configure --enable-check
    - uses: vapier/coverity-scan-action@v1
      with:
        project: r3
        email: yoanlin93+github@gmail.com
        token: ${{ secrets.COVERITY_TOKEN }}
